### ISSUE TITLE
UI layout for create/edit notes

### ISSUE THREAD

**Issue by lakshyajit165** [lakshyajit165/scribble#2]
- Looking for contributors for UI changes for the create/edit functionality for scribble webapp.

**Comment by lakshyaagr1105** [comment]
Hey lakshyajit165, I am  Lakshya and I am a FrontEnd Developer, can you please assign me this project, i am highly interested

**Comment by lakshyajit165** [comment]
@lakshyaagr1105 sure, but are you familiar with angular material ?

**Comment by lakshyaagr1105** [comment]
> @lakshyaagr1105 sure, but are you familiar with angular material ?

No

**Comment by lakshyajit165** [comment]
@lakshyaagr1105 i can assign you the issue if you could familiarize urself with angular material a little bit along with html, css and bootstrap

**Comment by lakshyaagr1105** [comment]
@lakshyajit165 sure

**Comment by riteshsoni123** [comment]
Hello @lakshyajit165 I would like to solve this issue. Can you please assign this to me?

**Comment by lakshyajit165** [comment]
Sure @riteshsoni123 have u worked on angular b4?

**Comment by lakshyajit165** [comment]
Closing as this is completed.
